# server.js
# BASE SETUP
# =============================================================================
# call the packages we need
express = require('express')
# call express
app = express()
# define our app using express
bodyParser = require('body-parser')
# configure app to use bodyParser()
# this will let us get the data from a POST
app.use bodyParser.urlencoded(extended: true)
app.use bodyParser.json()
port = process.env.PORT or 8080
# set our port
# ROUTES FOR OUR API
# =============================================================================
router = express.Router()
# get an instance of the express Router
# test route to make sure everything is working (accessed at GET http://localhost:8080/api)
router.get '/', (req, res) ->
  res.json message: 'hooray! welcome to our api!'
  return
# more routes for our API will happen here
# REGISTER OUR ROUTES -------------------------------
# all of our routes will be prefixed with /api
app.use '/api', router
# START THE SERVER
# =============================================================================
app.listen port
console.log 'Magic happens on port ' + port

# ---
# generated by js2coffee 2.0.4