// Generated by CoffeeScript 1.8.0
var app, bodyParser, express, port, router;

express = require('express');

app = express();

bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

port = process.env.PORT || 8080;

router = express.Router();

router.get('/', function(req, res) {
  res.json({
    message: 'hooray! welcome to our api!'
  });
});

app.use('/api', router);

app.listen(port);

console.log('Magic happens on port ' + port);
