// Generated by CoffeeScript 1.8.0
var Post, Route, app, bodyParser, express, mongoose, port, routeConfig;

express = require('express');

mongoose = require('mongoose');

bodyParser = require('body-parser');

Post = require('./app/models/post');

Route = require('./app/route');

app = express();

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

routeConfig = new Route(express, app);

port = process.env.PORT || 8080;

app.listen(port);

console.log('server listening on port ' + port);

mongoose.connect('mongodb://localhost/test');
