// Generated by CoffeeScript 1.8.0
var Route, glob, path;

glob = require('glob');

path = require('path');

Route = (function() {
  function Route(express, app) {
    var router;
    this.express = express;
    this.app = app;
    router = this.express.Router();
    glob.sync('./app/controllers/**/*.js').forEach(function(file) {
      var Controller;
      Controller = require(path.resolve(file));
      return new Controller(router);
    });
    this.app.use('/api', router);
  }

  return Route;

})();

module.exports = Route;
