// Generated by CoffeeScript 1.8.0
var Post, PostController, express;

express = require('express');

Post = require('../../app/models/post');

PostController = (function() {
  function PostController(router) {
    this.router = router;
    this.router.route('/post').get(this.get).post(this.post);
    this.router.route('/post/:id').get(this.get).put(this.put)["delete"](this["delete"]);
  }

  PostController.prototype.get = function(req, res) {
    var id, _ref;
    id = ((_ref = req.params) != null ? _ref.id : void 0) != null ? req.params.id : null;
    if (id != null) {
      return Post.findOne({
        _id: req.params.id
      }, function(err, post) {
        return res.json(err || post);
      });
    } else {
      return Post.find(function(err, posts) {
        return res.json(err || posts);
      });
    }
  };

  PostController.prototype.post = function(req, res) {
    var post;
    post = new Post(req.body);
    return post.save(function(err) {
      if (err) {
        return res.send(err);
      }
      return res.send({
        message: 'Post Added'
      });
    });
  };

  PostController.prototype.put = function(req, res) {
    return Post.findOne({
      _id: req.params.id
    }, function(err, post) {
      var prop;
      if (err) {
        return res.send(err);
      }
      for (prop in req.body) {
        post[prop] = req.body[prop];
      }
      return post.save(function(err) {
        if (err) {
          return res.send(err);
        }
        return res.json({
          message: 'Post updated!'
        });
      });
    });
  };

  PostController.prototype["delete"] = function(req, res) {
    return Post.remove({
      _id: req.params.id
    }, function(err, post) {
      if (err) {
        return res.send(err);
      }
      return res.json({
        message: 'Successfully deleted'
      });
    });
  };

  return PostController;

})();

module.exports = PostController;
